# Generated by Django 2.0 on 2018-01-28 01:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180128_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 28, 1, 40, 56, 788167, tzinfo=utc)),
        ),
    ]
