# Generated by Django 2.0.1 on 2018-01-25 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180125_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 25, 10, 56, 54, 373181, tzinfo=utc)),
        ),
    ]
