# Generated by Django 2.0.1 on 2018-01-25 23:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180126_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 25, 23, 34, 34, 658426, tzinfo=utc)),
        ),
    ]
