# Generated by Django 2.0.1 on 2018-01-26 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180126_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('forumid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Forum')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 26, 11, 17, 55, 932986, tzinfo=utc)),
        ),
    ]
