# Generated by Django 2.0.1 on 2018-01-26 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20180126_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 26, 12, 51, 53, 821380, tzinfo=utc)),
        ),
    ]
